# Default values for node projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: ghcr.io/salaboy/fmtok8s-frontend
  tag: v0.0.1
  pullPolicy: Always
c4p:
  enabled: true
debug: 
  enabled: false

env:
# enable this flag to use knative serve to deploy the app
knative:
  enabled: false
  # You can add traffic rules here to customize the Knative Serving rules
#  traffic:
#  - latestRevision: false
#    percent: 50
#    revisionName: fmtok8s-email-00001
#  - latestRevision: true
#    percent: 50
  eventing:
    enabled: false

prometheus:
  enabled: false

service:
  name: fmtok8s-frontend
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
  annotations:
resources:
  limits:
    cpu: "1"
    memory: 256Mi
  requests:
    cpu: "0.1"
    memory: 256Mi
probePath: /actuator/health
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  failureThreshold: 1
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
