{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-03-11T10:39:24Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      chore: release 0.0.203
    sha: 8035d22d3f1f590badbdd9f8e8b80f488a8d3862
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      chore: add variables
    sha: 5f86cabae3ce00eeba05bb268d848c25aa0b6400
  - author:
      email: salaboy@gmail.com
      name: salaboy
    branch: master
    committer:
      email: salaboy@gmail.com
      name: salaboy
    message: |
      adding label to service
    sha: 46b9cf11ba25dc8a711956d7c3859ef77cbe2a71
  gitHttpUrl: https://github.com/salaboy/fmtok8s-api-gateway
  gitOwner: salaboy
  gitRepository: fmtok8s-api-gateway
  name: '{{ .Chart.Name }}'
  releaseNotesURL: https://github.com/salaboy/fmtok8s-api-gateway/releases/tag/v0.0.204
  version: v0.0.204
status: {}
 
{{- end }}
